# Generated by Django 6.0.2 on 2026-04-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='telefono_docente',
            field=models.CharField(default='', help_text='Teléfono de contacto del docente', max_length=20),
        ),
    ]
