# Generated by Django 5.2.14 on 2026-05-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0003_solicitudespecial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudespecial',
            name='fecha_inicio',
            field=models.DateField(blank=True, help_text='Fecha de inicio de la recurrencia', null=True),
        ),
        migrations.AlterField(
            model_name='solicitudespecial',
            name='dia_semana',
            field=models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], default=0),
        ),
        migrations.AlterField(
            model_name='solicitudespecial',
            name='telefono_docente',
            field=models.CharField(default='', help_text='Teléfono de contacto del docente', max_length=20),
        ),
    ]
