# Generated by Django 5.2.14 on 2026-05-27 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0004_solicitudespecial_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='solicitud_especial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='solicitudes.solicitudespecial'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='solicitudes.solicitud'),
        ),
    ]
